#!/usr/bin/perl
use strict;
use warnings;
use Cwd;

#Useage: perl cat_fastq.pl list.txt
#This script will concatenate the four R1 and four R2 files that are generated by the NextSeq550 sequencer. 

#list = List of sample IDs
my $list = $ARGV[0];
my @ids;
my $wd = getcwd;

open IN, "<$list";
while (<IN>) {
    chomp;
    my $line = $_;
    push (@ids, $line);
}

foreach my $id (@ids) {
    system "cat $id\_L001_R1_001.fastq $id\_L002_R1_001.fastq $id\_L003_R1_001.fastq $id\_L004_R1_001.fastq > $id\_R1.fastq";
    system "cat $id\_L001_R2_001.fastq $id\_L002_R2_001.fastq $id\_L003_R2_001.fastq $id\_L004_R2_001.fastq > $id\_R2.fastq";
    print $id;
}
